#!/usr/bin/env bash
#
# Prepare a WVM installation: locate the ISOs, write a config, and create the disk.
#
# Deliberately explicit rather than magic. It reports what it found, names anything missing, and
# does not guess at paths. If an ISO is in an unexpected place, pass it with --iso.
#
# Usage:
#   scripts/prepare-install.sh [--iso <tiny11.iso>] [--drivers <virtio-win.iso>] [--dir <dir>]
#
# Exits non-zero if a required input is missing, so it can be used in a script.

set -euo pipefail

# --- defaults ---------------------------------------------------------------------------------

INSTALL_DIR="${WVM_DIR:-$HOME/wvm}"
DRIVER_ISO="${WVM_DRIVER_ISO:-$HOME/wvm-images/virtio-win.iso}"
INSTALL_ISO=""
DISK_GIB="${WVM_DISK_GIB:-64}"
MEMORY_MIB="${WVM_MEMORY_MIB:-8192}"
CPUS="${WVM_CPUS:-4}"

# --- arguments --------------------------------------------------------------------------------

while [ $# -gt 0 ]; do
    case "$1" in
        --iso)     INSTALL_ISO="$2"; shift 2 ;;
        --drivers) DRIVER_ISO="$2"; shift 2 ;;
        --dir)     INSTALL_DIR="$2"; shift 2 ;;
        --disk-gib) DISK_GIB="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "unknown argument: $1" >&2
            exit 2
            ;;
    esac
done

# --- locate the installer ISO ------------------------------------------------------------------

# Only guess if the caller did not say. Search the usual browser download locations for anything
# that looks like a Windows ISO, and report every candidate rather than silently picking one.
if [ -z "$INSTALL_ISO" ]; then
    echo "Locating the tiny11 ISO..."
    candidates=()
    for d in "$HOME/Downloads" "$HOME/Desktop" "$HOME/wvm-images"; do
        [ -d "$d" ] || continue
        while IFS= read -r f; do
            candidates+=("$f")
        done < <(find "$d" -maxdepth 2 -type f \( -iname '*tiny11*.iso' -o -iname '*win11*.iso' -o -iname '*windows*.iso' \) 2>/dev/null | sort)
    done

    # A browser download in flight is named *.crdownload; it is not usable yet and saying so is
    # more useful than reporting "not found".
    partial=$(find "$HOME/Downloads" -maxdepth 1 -type f -iname '*.crdownload' 2>/dev/null | head -1)
    if [ -n "$partial" ]; then
        size=$(du -h "$partial" 2>/dev/null | cut -f1)
        echo "  note: a download is still in progress ($size so far):"
        echo "        $partial"
        echo "        wait for it to finish, then re-run this script"
    fi

    if [ ${#candidates[@]} -eq 0 ]; then
        echo "ERROR: no Windows ISO found." >&2
        echo "  Looked in ~/Downloads, ~/Desktop and $HOME/wvm-images." >&2
        echo "  Pass one explicitly: $0 --iso /path/to/tiny11.iso" >&2
        exit 1
    fi

    INSTALL_ISO="${candidates[0]}"
    if [ ${#candidates[@]} -gt 1 ]; then
        echo "  found ${#candidates[@]} candidates; using the first:"
        for c in "${candidates[@]}"; do
            printf '    %s\n' "$c"
        done
        echo "  override with --iso if that is the wrong one"
    else
        echo "  found: $INSTALL_ISO"
    fi
fi

# --- validate ----------------------------------------------------------------------------------

fail=0

if [ ! -f "$INSTALL_ISO" ]; then
    echo "ERROR: installer ISO not found: $INSTALL_ISO" >&2
    fail=1
else
    size=$(stat -c %s "$INSTALL_ISO")
    human=$(du -h "$INSTALL_ISO" | cut -f1)
    echo "  installer: $INSTALL_ISO ($human)"
    # A partial ISO is the most likely failure: it downloads, then fails deep inside Windows Setup
    # with a confusing error. Warn on anything implausibly small.
    if [ "$size" -lt 1000000000 ]; then
        echo "    warning: only $human — Windows ISOs are normally several GB." >&2
        echo "             this may be a partial download." >&2
    fi
fi

if [ ! -f "$DRIVER_ISO" ]; then
    echo "ERROR: virtio driver ISO not found: $DRIVER_ISO" >&2
    echo "  Download it with:" >&2
    echo "    mkdir -p \"\$(dirname "$DRIVER_ISO")\"" >&2
    echo "    curl -L --http1.1 --limit-rate 2000k -o \"$DRIVER_ISO\" \\" >&2
    echo "      https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso" >&2
    fail=1
else
    echo "  drivers:   $DRIVER_ISO ($(du -h "$DRIVER_ISO" | cut -f1))"
fi

if [ "$fail" -ne 0 ]; then
    echo
    echo "Nothing was created. Fix the above and re-run." >&2
    exit 1
fi

# --- write the configs -------------------------------------------------------------------------

mkdir -p "$INSTALL_DIR"

cat > "$INSTALL_DIR/install.toml" <<EOF
# Generated by scripts/prepare-install.sh on $(date -Iseconds)
# Boots the Windows installer. Once Windows is installed, use wvm.toml instead.

name = "w11"
disk = "$INSTALL_DIR/disk.qcow2"
disk_gib = $DISK_GIB
memory_mib = $MEMORY_MIB
cpus = $CPUS
install_iso = "$INSTALL_ISO"
driver_iso = "$DRIVER_ISO"
firmware = "uefi"
guest_port = 48273
forward_port = 48274
EOF

cat > "$INSTALL_DIR/wvm.toml" <<EOF
# Generated by scripts/prepare-install.sh on $(date -Iseconds)
# The long-lived definition: boots from disk, no installer attached.
#
# Keeping the installer out of this file is the point. An ISO accidentally left bootable would
# drop a working VM back into Windows Setup.

name = "w11"
disk = "$INSTALL_DIR/disk.qcow2"
disk_gib = $DISK_GIB
memory_mib = $MEMORY_MIB
cpus = $CPUS
driver_iso = "$DRIVER_ISO"
firmware = "uefi"
guest_port = 48273
forward_port = 48274
EOF

echo "  wrote:     $INSTALL_DIR/install.toml"
echo "  wrote:     $INSTALL_DIR/wvm.toml"

# --- create the disk ---------------------------------------------------------------------------

if [ -f "$INSTALL_DIR/disk.qcow2" ]; then
    echo "  disk:      already exists, leaving it alone"
else
    qemu-img create -f qcow2 "$INSTALL_DIR/disk.qcow2" "${DISK_GIB}G" >/dev/null
    echo "  disk:      created ${DISK_GIB} GiB qcow2"
fi

# --- report ------------------------------------------------------------------------------------

cat <<EOF

Ready.

  demo the command line first, so you can see what will run:
    wvm vm cmdline  --config $INSTALL_DIR/install.toml

  then install:
    wvm vm start    --config $INSTALL_DIR/install.toml --timeout 300
    wvm vm log      --config $INSTALL_DIR/install.toml --lines 60

  In Windows Setup, when asked where to install:

    1. Choose "Load driver"
    2. Browse to the driver CD -> viostor -> w11 -> amd64
    3. Select "Red Hat VirtIO SCSI controller"
    4. The ${DISK_GIB} GiB disk appears; select it and continue

  Without step 1-3, Setup reports no disks at all. That is expected, not a fault.

  After Windows is installed, use the other config so the installer is not attached:
    wvm vm shutdown --config $INSTALL_DIR/install.toml
    wvm vm start    --config $INSTALL_DIR/wvm.toml
EOF
